- name: This playbook is to install creat
  hosts: cart 
  become: true 
  tasks:
  - name: This task is to NodeJS repos
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  
  - name: This task is to Install NodeJS
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: This task is to check user roboshop
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true  

  - name: This task is to add user roboshop
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0

  - name: This task is to check app directory
    ansible.builtin.stat:
      path: /app
    register: status

  - name: This task is to display app directory
    ansible.builtin.debug:
      msg: "ouput : {{status}}"

  - name: This task is to create app directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: status.stat.exists == False

  - name: This task is to download the application code to created app directory.
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: This task is to unzip
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: download the dependencies.
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: This task is to copy the cart Service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: This task is to Load the service.
    ansible.builtin.systemd:
      daemon_reload: true
  
  - name: This task is to Start & Enable catalogue Service
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes