- name: This playbook is to install the dispatch module
  hosts: dispatch 
  become: true
  tasks:
  - name: Install GoLang
    ansible.builtin.yum:
      name: golang
      state: installed

  - name: This task is to check user roboshop
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true  

  - name: This task is to add user roboshop
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0

  - name: This task is to check app directory
    ansible.builtin.stat:
      path: /app
    register: status

  - name: This task is to display app directory
    ansible.builtin.debug:
      msg: "ouput : {{status}}"

  - name: This task is to create app directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: status.stat.exists == False
  
  - name: This task is to download the application code to created app directory.
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp

  - name: This task is to unzip
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes

  - name: download the dependencies
    ansible.builtin.command: go mod init dispatch
    ansible.builtin.command: go get
    ansible.builtin.command: go build

  - name: This task is to copy the dispatch Service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service
  
  - name: This task is to Load the service.
    ansible.builtin.systemd:
      daemon_reload: true

  - name: This task is to Start & Enable disaptch Service
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes

  